projectName=gzac-backend-template
projectGroup="com.ritense.valtimo"
projectVersion=1.0.0

org.gradle.jvmargs=-Xms128m -Xmx1024m -Duser.timezone=UTC
org.gradle.welcome=never

kotlinVersion=2.1.20
springBootVersion=3.5.14
springDependencyManagementVersion=1.1.7
dockerComposePluginVersion=0.17.12
mockitoKotlinVersion=5.4.0
ktlintVersion=12.2.0
spotlessVersion=7.0.3
ideaExt=1.1.10

freemarkerPluginVersion=8.3.3
smtpmailPluginVersion=2.0.2

valtimoVersion=13.26.0.RELEASE
