projectName=gzac-backend-template
projectGroup="com.ritense.valtimo"
projectVersion=1.0.0

org.gradle.jvmargs=-Xms128m -Xmx1024m -Duser.timezone=UTC
org.gradle.welcome=never

kotlinVersion=1.9.25
springBootVersion=3.2.5
springDependencyManagementVersion=1.1.6
dockerComposePluginVersion=0.17.12
postgresqlDriverVersion=42.7.4
mockitoKotlinVersion=5.4.0
camundaBpmAssertVersion=15.0.0

nettyResolverDnsNativeMacOsVersion=4.1.105.Final
ktlintVersion=12.0.3
spotlessVersion=6.23.3
ideaExt=1.1.7

valtimoVersion=12.23.1.RELEASE
