projectName=gzac-backend-template
projectGroup="com.ritense.valtimo"
projectVersion=1.0.0

org.gradle.jvmargs=-Xms128m -Xmx1024m -Duser.timezone=UTC
org.gradle.welcome=never

kotlinVersion=2.1.20
springBootVersion=3.4.7
springDependencyManagementVersion=1.1.7
dockerComposePluginVersion=0.17.12
postgresqlDriverVersion=42.7.8
mockitoKotlinVersion=5.4.0

nettyResolverDnsNativeMacOsVersion=4.2.0.Final
ktlintVersion=12.2.0
spotlessVersion=7.0.3
ideaExt=1.1.10

freemarkerPluginVersion=8.3.3
smtpmailPluginVersion=2.0.2

valtimoVersion=13.23.0.RELEASE
